name: CI
on: [pull_request, workflow_dispatch]

jobs:
  see-payload:
    runs-on: ubuntu-latest
    steps:
    - name: write payload
      run: |
        cat $GITHUB_EVENT_PATH > payload.json
    - name: Upload payload
      uses: actions/upload-artifact@v1
      with:
        name: payload
        path: payload.json

    - name: look at stuff
      run: echo $STUFF
      env: 
        STUFF: "${{ github.event.pull_request.number }}"
  demo:
    strategy:
      fail-fast: false
      matrix:
        runs: [ubuntu-latest] #[ubuntu-ml-gpu, ubuntu-ci-64cpu]
    runs-on: ${{ matrix.runs }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: test
      run: | 
        pip install wheel tensorflow wandb numpy tabulate requests pandas
        python train.py
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
        WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
  
    - name: Get Runs Using SHA
      uses: machine-learning-apps/wandb-action@master
      id: wandb
      with:
        PROJECT_NAME: ${{ format('{0}/{1}', secrets.WANDB_ENTITY, secrets.WANDB_PROJECT) }}
        FILTER_GITHUB_SHA: ${{ github.sha }}
        BASELINE_TAGS: "['baseline', 'reference']"
        DISPLAY_METRICS: "['loss', 'acc', 'val_loss', 'val_acc', '_runtime']"
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        DEBUG: 'true'

    - name: See metrics
      run: cat wandb_report.csv

    - name: See PR Number
      run: echo "PR number is $PRNUM"
      env: 
        PRNUM: ${{ github.event.pull_request.number }}

    - name: display statistics
      if: steps.wandb.outputs.BOOL_COMPLETE == 'true'
      run: |
        python _action/wandb_results.py
      env:
        PR_NUM: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
